//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace omniBill.InnerComponents.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Customer
    {
        public Customer()
        {
            this.DraftInvoices = new HashSet<DraftInvoice>();
        }

        public int customerId { get; set; }
        public string customerName { get; set; }
        public string street { get; set; }
        public string postCode { get; set; }
        public string city { get; set; }
        public string phoneNumber { get; set; }
        public string email { get; set; }
    
        public virtual ICollection<DraftInvoice> DraftInvoices { get; set; }
    }
}
