//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace omniBill.InnerComponents.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceLine
    {
        public int invoiceId { get; set; }
        public int itemId { get; set; }
        public int quantity { get; set; }
        public string comment { get; set; }
    
        public virtual DraftInvoice DraftInvoice { get; set; }
        public virtual Item Item { get; set; }
    }
}
