//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace omniBill.InnerComponents.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public Item()
        {
            this.InvoiceLines = new HashSet<InvoiceLine>();
        }
    
        public int itemId { get; set; }
        public string itemName { get; set; }
        public string descr { get; set; }
        public decimal price { get; set; }
        public int vatId { get; set; }
    
        public virtual ICollection<InvoiceLine> InvoiceLines { get; set; }
        public virtual VatGroup VatGroup { get; set; }
    }
}
