//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace omniBill.InnerComponents.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTable
    {
        public UserTable()
        {
            this.DraftInvoices = new HashSet<DraftInvoice>();
        }
    
        public int userId { get; set; }
        public string companyName { get; set; }
        public string contactName { get; set; }
        public string street { get; set; }
        public string postCode { get; set; }
        public string city { get; set; }
        public string bankName { get; set; }
        public string bankAccount { get; set; }
        public string businessId { get; set; }
        public string phoneNumber { get; set; }
        public string email { get; set; }
    
        public virtual ICollection<DraftInvoice> DraftInvoices { get; set; }
    }
}
