//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace omniBill.InnerComponents.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class VatGroup
    {
        public VatGroup()
        {
            this.Items = new HashSet<Item>();
        }
    
        public int vatId { get; set; }
        public double percentage { get; set; }
    
        public virtual ICollection<Item> Items { get; set; }
    }
}
